version: "3.5"

services:

  cache:
    container_name: dev_pledge_cache
    image: redis
    restart: always
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes


networks:
  default:
    name: devpledge_cache

