version: "3.5"

services:

  cache:
    container_name: dev_pledge_cache
    image: redis
    restart: always
    volumes:
      - ./data:/data
    entrypoint: redis-server --appendonly yes

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:cache:6379
    ports:
    - 8081:8081

networks:
  default:
    name: devpledge_cache

